{% set python_min = "3.10" %}
{% set name = "xcube-cmems" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-cmems/archive/v{{ version }}.tar.gz
  sha256: 643b997bb0298a29427e1cc94a849b982ba9b734517e2a8ac21358eafc61820c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.9.0
    - pip
  run:
    # Python
    - python >={{ python_min }}
    # Required
    - copernicusmarine >=2.1.1
    - numpy <2.0.0
    - pandas
    - xarray >=2024.7.0
    - xcube >=1.9.1
test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_cmems

about:
  summary: xcube plugin for the Copernicus Marine Service (CMEMS) API
  home: https://github.com/xcube-dev/xcube-cmems
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cmems is an xcube plugin which can generate data cubes from the Copernicus Marine Service (CMEMS) API.
  doc_url: https://github.com/xcube-dev/xcube-cmems/blob/master/README.md
  dev_url: https://github.com/xcube-dev/xcube-cmems

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - forman
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
