{% set name = "xcube-cmems" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cmems/archive/v{{ version }}.tar.gz
  sha256: 78e63aa2cdeaa4c88310be387ef163ba9ce0ed9b290419377c464d8925ef50f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    # Python
    - python >=3.8
    # Required
    - aiohttp >=3.8
    - gdal >=3.0,<3.6.3
    - lxml >=4.9.1
    - nest-asyncio >=1.5
    - owslib
    - pydap >=3.3.0
    - pyproj
    - tenacity
    - xcube >=0.12.1
    - zarr
test:
  imports:
    - xcube_cmems

about:
  summary: xcube plugin for the Copernicus Marine Service (CMEMS) API
  home: https://github.com/dcs4cop/xcube-cmems
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cmems is an xcube plugin which can generate data cubes from the Copernicus Marine Service (CMEMS) API.
  doc_url: https://github.com/dcs4cop/xcube-cmems/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cmems

extra:
  recipe-maintainers:
    - TejasMorbagal
    - TonioF
    - AliceBalfanz
    - pont-us
    - forman
